name: Build

on:
  push:
    branches:
      - main
  schedule:
    # Run everyday (after docker-articulate-node-images since we build off those)
    - cron: "0 1 * * *"

env:
  IMAGE: articulate/articulate-node-images
  LATEST: 14-stretch-slim

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - 12/buster-slim
          - 12/stretch-slim
          - 14/stretch-slim
          - 14/buster-slim
          - 16/stretch-slim
          - 16/buster-slim
          - 16/bullseye-slim
          - 18/bullseye-slim
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build info
        id: meta
        run: |
          TAG="${IMAGE}:$(echo "${{ matrix.dockerfile }}" | sed 's#/#-#')"
          echo "cache=${TAG}" >> $GITHUB_OUTPUT

          [ "$TAG" == "${IMAGE}:${LATEST}" ] && TAG="${TAG},${IMAGE}:latest"
          echo "tags=${TAG}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=${{ steps.meta.outputs.cache }}
          cache-to: type=inline
